jobs:

- template: azure-pipelines-template.yml
  parameters:
    platform: Linux
    vmImage: ubuntu-16.04
    toolchain: stable

- template: azure-pipelines-template.yml
  parameters:
    platform: Linux
    vmImage: ubuntu-16.04
    toolchain: beta

- template: azure-pipelines-template.yml
  parameters:
    platform: MacOS
    vmImage: macOS-10.13
    toolchain: stable

- template: azure-pipelines-template.yml
  parameters:
    platform: MacOS
    vmImage: macOS-10.13
    toolchain: beta

- template: azure-pipelines-template.yml
  parameters:
    platform: Windows
    vmImage: vs2017-win2016
    toolchain: stable

- template: azure-pipelines-template.yml
  parameters:
    platform: Windows
    vmImage: vs2017-win2016
    toolchain: beta
