jobs:

- template: azure-pipelines-template.yml
  parameters:
    platform: Linux
    image: ubuntu-16.04

- template: azure-pipelines-template.yml
  parameters:
    platform: MacOS
    image: macOS-10.13

- template: azure-pipelines-template.yml
  parameters:
    platform: Windows
    image: vs2017-win2016

