[package]
name = "skia-safe"
version = "0.1.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[features]
default = []
vulkan = ["rust-skia/vulkan"]

[dependencies]
rust-skia = { path = "../rust-skia" }
