inputs:
  target:
    description: 'The target to build.'
    required: true

  features:
    description: 'The features to build.'
    required: true

  runBinaries:
    description: 'Run test cases and examples?'
    default: false
    required: false

runs:
  using: 'composite'
  steps:
  - name: 'Add Rust target ${{ inputs.target }}'
    run: |
      rustup target add ${{ inputs.target }}
    shell: bash
  
  - name: 'Build all targets in skia-safe for ${{ inputs.target }} with features "${{ inputs.features }}"'
    run: |
      cargo clean
      (cd skia-safe && cargo build --release --features "${{ inputs.features }}" --all-targets --target ${{ inputs.target }} -vv)
    shell: bash
