name: 'Rust Skia'
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, macOS-10.15, ubuntu-20.04]
        edition: [stable, beta]
      fail-fast: false
      include:
        - os: 'windows-2019'
          host-target: 'x86_64-pc-windows-msvc'
          host-os: 'Windows'
          features: 'gl,vulkan,textlayout'

        - os: 'macOS-10.15'
          host-target: 'x86_64-apple-darwin'
          host-os: 'macOS'
          features: 'gl,vulkan,textlayout,metal'

        - os: 'ubuntu-20.04'
          host-target: 'x86_64-unknown-linux-gnu'
          host-os: 'Linux'
          features: 'gl,vulkan,textlayout'

    steps:
    - name: 'Build on ${{ matrix.host-os }} Host with Host Target ${{ matrix.host-target }}'
      uses: ./.github/actions/build-host
      with:
        host-os: ${{ matrix.host-os }}
        rust-edition: ${{ matrix.edition }}
        host-target: ${{ matrix.host-target }}
        features: ${{ matrix.features }}

  rustfmt:
    name: Check Rust Formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable 
          rustup component add rustfmt
      - name: Generate missing bindings.rs file
        run: |
          echo > skia-bindings/src/bindings.rs
      - run: | 
          cargo fmt -- --check
