# Supplemental workflow for testing alternative build configurations.

name: 'supplemental-builds'
on:
  push:
    branches-ignore:
      - release
  pull_request:
    branches-ignore:
      - release
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: 'supplemental-builds-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  linux-local-build:
    runs-on: ubuntu-20.04
    container: ghcr.io/pragmatrix/rust-skia-linux:latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Prepare Rustup
      run: (cd /github/home && ln -s /root/.cargo)
    
    - name: Update Rustup and Rust
      run: rustup update
    
    - name: Configure Rust Toolchain
      run: rustup default stable
    
    - name: Install Clippy
      run: rustup component add clippy
    - name: 'Install Rust target x86_64-unknown-linux-gnu'
      shell: bash
      run: |
        rustup target add x86_64-unknown-linux-gnu
    
    - name: 'Test local builds (#527)'
      shell: bash
      run: |
        make test-local-build
